version: '3.5'

volumes:
  data:

services:
  database:
    image: postgres
    ports:
      - 5440:5432
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - data:/var/lib/postgresql/data
